### ISSUE TITLE
issues with pulseaudio via docker

### ISSUE THREAD

**Issue by tedr56** [rubenbe/docker-spotifyDLNA#3]
Hi.
I've been trying to make this but it seems the pulseaudio config is not simple.
First, it seems to detect it is a system-wide installation and lookup for cookie in /var/run/pulse/.config/pulse/cookie
At the end of logs I get permission issue on /root/.config/pulse
I've got a cookie in my home folder, and I tried to map it to sereval folders in container, but doesn't seem to care.
What is the right way to detect my user cookie?

Thanks.

```
++ dbus-daemon --system --fork
++ pulseaudio --log-level=1 --system
++ sleep 1
++ /librespot-0.2.0/target/release/librespot -n spotifydlna -b 320 --disable-audio-cache --initial-volume 100 --device-type speaker -u *** -p '***'
W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
[2022-03-10T23:16:07Z INFO  librespot] librespot 0.2.0 UNKNOWN (Built on 2021-05-12, Build ID: OsstSxGP)
[2022-03-10T23:16:07Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
W: [pulseaudio] authkey.c: Failed to open cookie file '/var/run/pulse/.config/pulse/cookie': Permission denied
W: [pulseaudio] authkey.c: Failed to load authentication key '/var/run/pulse/.config/pulse/cookie': Permission denied
W: [pulseaudio] authkey.c: Failed to open cookie file '/var/run/pulse/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/var/run/pulse/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/var/run/pulse/.config/pulse/cookie': Permission denied
W: [pulseaudio] authkey.c: Failed to load authentication key '/var/run/pulse/.config/pulse/cookie': Permission denied
E: [pulseaudio] module.c: Failed to load module "module-native-protocol-unix" (argument: "auth-anonymous=1"): initialization failed.
[2022-03-10T23:16:07Z INFO  librespot_core::session] Authenticated as "***" !
[2022-03-10T23:16:07Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudio sink with format: S16
[2022-03-10T23:16:07Z INFO  librespot_core::session] Country: "FR"
++ pulseaudio-dlna --codec wav --renderer-urls http://http://192.168.1.251:1430/description.xml
03-10 23:16:08 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
03-10 23:16:08 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
03-10 23:16:08 pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (9)
03-10 23:16:10 pulseaudio_dlna.daemon                         INFO     Attaching application to pulseaudio (9)
03-10 23:16:10 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
03-10 23:16:10 pulseaudio_dlna.application                    INFO     Using version: 0.6.1
03-10 23:16:10 pulseaudio_dlna.application                    INFO     Binding to *:8080
03-10 23:16:10 pulseaudio_dlna.application                    INFO     Encoder settings:
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="False">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="False" sample-rate="44100" channels="2">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="False">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="False">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="False" bit-rate="192">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
03-10 23:16:10 pulseaudio_dlna.application                    INFO     Codec settings:
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="0" mime_type="audio/aac" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="0" mime_type="audio/flac" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="False" priority="0" mime_type="audio/mp3" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="0" mime_type="audio/ogg" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="0" mime_type="audio/opus" backend="generic">
03-10 23:16:10 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="24" mime_type="audio/wav" backend="generic">
03-10 23:16:10 pulseaudio_dlna.streamserver                   CRITICAL The streaming server could not bind to your specified port (8080). Perhaps this is already in use? The application cannot work properly!
Failed to create secure directory (/root/.config/pulse): Permission denied
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 617, in run
    self._connect(signals)
  File "/usr/lib/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 55, in _connect
    self.bus = self._get_bus()
  File "/usr/lib/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 139, in _get_bus
    if MODULE_DBUS_PROTOCOL not in modules:
TypeError: argument of type 'NoneType' is not iterable
03-10 23:16:10 pulseaudio_dlna.holder                         WARNING  Could no connect to http://http://192.168.1.251:1430/description.xml. Connection refused.
```

**Comment by rubenbe** [comment]
Hi 

The container should not interact with pulseaudio on the host. As it is meant to run headless.
Can you send me the docker/podman command that you use to start the container?

Also I see this weird URL: `http://http://192.168.1.251:1430/description.xml`
It might indicate that you have an unneeded `http://` somewhere.

**Comment by tedr56** [comment]
Thanks for the reply.
I indeed made a typo here.
The address is my kodi dlna server instance.
If I remove all the volumes I added for pulseaudio I get a port 8080 already in use wich is normal.
Any way to modify that?


```
version: '3.8'
services:
  spotifydlna:
    image: rubenbe/spotifydlna
    container_name: spotifydlna
    restart: unless-stopped

    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - LIBRESPOT_NAME=spotifydlna
      - PULSEAUDIO_DLNA_OPTS=--codec wav --renderer-urls http://192.168.1.251:1430
      - LIBRESPOT_OPTS=-u ******* -p ******
    network_mode: "host"
```

```
++ dbus-daemon --system --fork
++ pulseaudio --log-level=1 --system
++ sleep 1
++ /librespot-0.2.0/target/release/librespot -n spotifydlna -b 320 --disable-audio-cache --initial-volume 100 --device-type speaker -u *** -p '***'
W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set.
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
[2022-03-11T13:26:00Z INFO  librespot] librespot 0.2.0 UNKNOWN (Built on 2021-05-12, Build ID: OsstSxGP)
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.


W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
[2022-03-11T13:26:00Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
W: [pulseaudio] authkey.c: Failed to open cookie file '/var/run/pulse/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/var/run/pulse/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/var/run/pulse/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/var/run/pulse/.pulse-cookie': No such file or directory
[2022-03-11T13:26:00Z INFO  librespot_core::session] Authenticated as "***" !
[2022-03-11T13:26:00Z INFO  librespot_core::session] Country: "FR"
[2022-03-11T13:26:00Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudio sink with format: S16
++ pulseaudio-dlna --codec wav --renderer-urls http://192.168.1.251:1430
03-11 13:26:01 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
03-11 13:26:01 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
03-11 13:26:01 pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (9)
03-11 13:26:03 pulseaudio_dlna.daemon                         INFO     Attaching application to pulseaudio (9)
03-11 13:26:03 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
03-11 13:26:04 pulseaudio_dlna.application                    INFO     Using version: 0.6.1
03-11 13:26:04 pulseaudio_dlna.application                    INFO     Binding to *:8080
03-11 13:26:04 pulseaudio_dlna.application                    INFO     Encoder settings:
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="False">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="False" sample-rate="44100" channels="2">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="False">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="False">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="False" bit-rate="192">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
03-11 13:26:04 pulseaudio_dlna.application                    INFO     Codec settings:
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="0" mime_type="audio/aac" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="0" mime_type="audio/flac" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="False" priority="0" mime_type="audio/mp3" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="0" mime_type="audio/ogg" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="0" mime_type="audio/opus" backend="generic">
03-11 13:26:04 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="24" mime_type="audio/wav" backend="generic">
03-11 13:26:04 pulseaudio_dlna.streamserver                   CRITICAL The streaming server could not bind to your specified port (8080). Perhaps this is already in use? The application cannot work properly!
Connection failure: Connection refused

pa_context_connect() failed: Connection refused
Process Process-2:

**Comment by rubenbe** [comment]
First: you accidentally pasted credentials in the docker-compose snippet! (I edited to hide them, but consider them compromised)

You should be able to change the port. If you check the pulseaudio-dlna options:
https://github.com/masmu/pulseaudio-dlna/blob/4472928dd23f274193f14289f59daec411023ab0/pulseaudio_dlna/__main__.py#L47

Adding `-p 1234` to `PULSEAUDIO_DLNA_OPTS` should do the job (I couldn't test it myself)

**Comment by rubenbe** [comment]
Close due to no activity anymore.
